apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.serviceName }}
webhooks:
  - name: kritis-validation-hook.grafeas.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ .Values.serviceName }}
        namespace: {{ .Values.serviceNamespace }}
