apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.preinstall.pod }}
  namespace: {{ .Values.serviceNamespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  serviceAccountName: kritis-preinstall-serviceaccount
  containers:
  - name: {{ .Values.preinstall.pod }}
    image: {{ .Values.preinstall.pod.image }}
    command: {{ .Values.preinstall.pod.command }}
