apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: attestationauthorities.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  names:
    kind: AttestationAuthority
    plural: attestationauthorities
  scope: Namespaced
